name: build_base_images

on:
  push:
    paths:
      - .github/workflows/build_base_images.yml
      - deployment/nginx/*

jobs:
  publish-base-nginx-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    - name: Build the base-nginx Docker image
      run: |
        docker build ./deployment/nginx/ --tag ghcr.io/atalykov/ip2location-nginx-docker/nginx-ip2location:latest
        docker push ghcr.io/atalykov/ip2location-nginx-docker/nginx-ip2location:latest
